### ISSUE TITLE
[low/ED] link to WAI statement

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-statements#105]
from @bakkenb & @sharronrush 

Add link to the [WAI statement](https://www.w3.org/WAI/about/accessibility-statement/) as another example.

_/me notes after it's polished, which should be within the next day or so :-)_

I *mildly* think add to the list on https://www.w3.org/WAI/planning/statements/ under "Examples of accessibility statements" (and *not* include it in the secondary nav)

**Comment by bakkenb** [comment]
+1 strongly for NOT including WAI statement in secondary nav like minimal and complete.

Location proposed by @slhenry sounds great.

**Comment by nitedog** [comment]
Reverted change (was supposed to be Pull Request rather than Commit)
