### ISSUE TITLE
Clarity needed for organizations monitoring

### ISSUE THREAD

**Issue by iamjolly** [w3c/wai-statements#11]
> For procurers and persons or organizations monitoring to understand the level of accessibility/conformance

Is "organizations monitoring" meant to be a governmental or compliance agency which monitors the state of accessibility of a site or application? Perhaps the wording of that objective needs clarification.

**Comment by AccessibilityNL** [comment]
Tried to keep it very general so it covers more ground. This is meant to include both your examples. But it could also cover employees of a private company who want to know about the accessibility of their company website and anyone interested in the accessibility of a certain website. Could change it from: 
"For procurers and persons or organizations monitoring to understand the level of accessibility/conformance" 
to:
"For procurers and persons or organizations who wish to understand the level of accessibility/conformance of a website or mobile application"
