### ISSUE TITLE
Make contribution and customization easy

### ISSUE THREAD

**Issue by rvantonisse** [w3c/wai-statements#121]
Contribution for and customization of the statement generator is possible, but to make this easier for developers and / or implementors a few tasks need to be done.

## Contribution enhancements

These "user stories" define enhancements for project setup and organization and are not related to actual functionality and content of the Statement Generator.
The goal is to lower the entry level for code development.

- [ ] I want to add a custom form element
- [ ] I want to add an utility script to the project
- [ ] I want to know how to write code for this project

## Customization enhancements

These "user stories" define enhancements that probably will produce new functionality to work with the Statement Generator and how content is created for this tool.
The goal is to lower the entry level (human readable) to content development of this tool.

- [ ] I want to create a translated version
- [ ] I want to add / remove sections in the statement form
- [ ] I want to add / remove fields in the statement form
- [ ] I want to add to / remove from the statement output

**Comment by yatil** [comment]
@rvantonisse I think most of that should be covered by better website documentation I need to work on and some documentation that @slhenry is providing. Let’s make sure to not duplicate efforts here. :-)

**Comment by rvantonisse** [comment]
> @rvantonisse I think most of that should be covered by better website documentation I need to work on and some documentation that @slhenry is providing. Let’s make sure to not duplicate efforts here. :-)

I am purely looking at statement generator specific things to tackle. If this conflicts or feels as duplicate work for the wai-statements please do let me know! But I think by "website" documentation you refer to either content published at the W3C site and / or wai-website-theme on Github?

**Comment by nitedog** [comment]
Guidance has been added to the documentation, please re-open if you think it does not sufficiently address your comment.
