### ISSUE TITLE
_external data does not seem to get picked up by Jekyll

### ISSUE THREAD

**Issue by rvantonisse** [w3c/wai-statements#122]
@yatil trying to run the wai-statements with the implementation of external data / git submodules but run into a problem.

Jekyll does not seem to pick up the external data from the symlinked data.

- I have the repository cloned.
- Git submodules working (`_external/data` folder with contents and .git initialized)
- _data folder with symlinked files from _external
- Jekyll serve running without generated errors.

Page looks ok, but navigation on left side missing.

does anything else needs to be updated (e.g. _config.yml)? Did anything else change?

Resetting repository to pre git submodule version seem to return the navigation back on screen.

**Comment by yatil** [comment]
Did you run a `git submodule update --recursive --remote` locally? I can take a look once I’m back from vacation next week. Sorry for the inconvenience.

**Comment by rvantonisse** [comment]
> Did you run a `git submodule update --recursive --remote` locally?

No, but I ran this command instead `git submodule update --init --recursive` following this guide: https://github.blog/2016-02-01-working-with-submodules/ which added the files and symlinks.

But by al means enjoy your holiday! The answer can definitely await until you are back.

**Comment by yatil** [comment]
I always use the command I posted above. Will look into it when I’m back :-D

**Comment by yatil** [comment]
@rvantonisse It works here. I did a `git pull`, then a `git submodule update --recursive --remote` to get the latest submodule (which I have checked in now). `bundle exec jekyll serve --livereload --incremental` works then and shows the left navigation.

Thinking about it, maybe there was an old version of the navigation file checked in?

Can you try again and let me know if you still have issues?

**Comment by rvantonisse** [comment]
> `git submodule update --recursive --remote`

Did it!

**Comment by yatil** [comment]
Hooray! /me makes notes to better document it :-)

**Comment by ATLowther** [comment]
I am having this same issue. Assuming that I have correctly followed the suggestion in here, it did not work for me.

I am wanting to use this as an integration to a current website of mine. I am wanting to generate the _site folder for access to the contents.

1. cloned the repo
2. cd repo
3. bundle update (bundle install throws an error)
4. bundle exec jekyll build

- This is where I get the error `jekyll 3.8.5 | Error:  No such file or directory @ rb_sysopen - /path/wai-statements/_data/wcag.yml`

Running `git submodule update --recursive --remote` returns nothing and following it with `bundle exec jekyll build` then yields the same error as before.

**Comment by yatil** [comment]
@ATLowther Sorry, we cannot do tech support external uses of our repositories. Unfortunately, I also have no idea why it is not working for you.
