### ISSUE TITLE
[Question] Standalone version of A11y's Statement?

### ISSUE THREAD

**Issue by jorgeponto** [w3c/wai-statements#125]
Do you have already a standalone version? A version non-dependent from W3C website.

**Comment by rvantonisse** [comment]
> Do you have already a standalone version? A version non-dependent from W3C website.

Yes and no;

Currently the way to work with a stand-alone variant of the statement generator is described under [Installation as stand-alone](https://github.com/w3c/wai-statements#installation-as-stand-alone) in the README.md

Other ways to work with the statement generator as a stand-alone are not present.

**Comment by jorgeponto** [comment]
I created a standalone version according to the description of Installation ... It is at: https://github.com/jorgeponto/generator-standalone . The [initial stand-alone](http://www.acessibilidade.tk/index-original.html) works well. Then I [start to translate to PT](http://www.acessibilidade.tk/index.html) and I don't know why the section page create doesn't appear (is hidden). I tried to made [a version only w/ the section structure](http://www.acessibilidade.tk/jorge.html) for then starting to compose my sections and content, but also the same behaviour: the section page create is hidden. I passed already hours trying to get the diffs :-) . Can you help me?

**Comment by rvantonisse** [comment]
@jorgeponto The generator works with hashed urls to show pages create and preview. So if youi want to show the "create" page, you need to have no hash or a hash with create in it like `my/url/to/the/statement/#create`.
The application can work with either no hash, with the word "create" or "preview" in it. If either of these words are missing in the hash, the application shows nothing. (e.g. `#my-internal-link` does nothing but `#create-my-internal-link` will show the create page and navigates to `create-my-internal-link` if set) Hope this answers your question.

I have create an issue to tackle this in a more human friendly way #126

**Comment by jorgeponto** [comment]
@rvantonisse If I understood correctly if I put http://acessibilidade.tk/generator-standalone/jorge.html#create the section create will appear but doesn't. The same to http://acessibilidade.tk/generator-standalone/index.html#create (my attempt to have a more content cleaner.
