### ISSUE TITLE
[minor] tweak date information wording

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-statements#130]
In: https://www.w3.org/WAI/planning/statements/generator/#create

In Date information, change:
> Writing out the month makes the date clearer internationally (eg. "1 February 2019" rather than "01/02/2019", which is ambiguous).

to:
> You can use any date format. Write out the month to make it clear internationally. (The date format 01-02-2022 is ambiguous — it is 2 January in some places and 1 February in some places.)

_(from new addition to [Style Guide, Dates](https://www.w3.org/WAI/EO/wiki/Style#Dates) based on https://github.com/w3c/wai-website/issues/213)_

**Comment by nitedog** [comment]
This seems to reflect local settings. [Similar issue on the ATAG Report Tool](https://github.com/w3c/wai-atag-report-tool/issues/130) was previously resolved by @hidde -- hopefully we can reuse the solution here

**Comment by nitedog** [comment]
AFAIK, this issue was addressed.
