### ISSUE TITLE
The statement generator does not include boilerplate which may be required in EU member states

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-statements#132]
### Expected behavior

Public sector bodies may be required to follow this model accessibility statement.

[COMMISSION IMPLEMENTING DECISION (EU) 2018/1523 ... establishing a model accessibility statement](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32018D1523&from=EN)

Annex, Section 1 "Mandatory Content Requirements":

> ACCESSIBILITY STATEMENT
> 
> [Name of public sector body] is committed to making its [website(s)] [and] [mobile application(s)] accessible, in accordance with [national legislation transposing Directive (EU) 2016/2102 of the European Parliament and of the Council (1)].
> 
> This accessibility statement applies to [insert scope of statement, e.g. website(s)/mobile application(s i ) to which the statement applies, as appropriate].
> 
> Compliance status ii
> 
> (a) iii
> 
> [This] [These] [website(s)] [mobile application(s)] [is] [are] fully compliant with [xxx iv].
> 
> (b) v
> 
> [This] [These] [website(s)] [mobile application(s)] [is] [are] partially compliantvi with [xxx vii], due to [the non-compliance(s)] [and/or] [the exemptions] listed below.
> 
> (c) viii
> 
> [This] [These] [website(s)] [mobile application(s)] [is] [are] not compliant with [xxx ix]. The [non-compliance(s)] [and/or] [the exemptions] are listed below.
> 
> Non-accessible content x
> 
> The content listed below is non-accessible for the following reason(s):
> 
> (a)
> 
> non-compliance with the [national legislation]
> 
> [List the non-compliance(s) of the website(s)/mobile application(s), and/or, describe which section(s)/content/function(s) are not yet compliant xi].
> 
> (b)
> 
> disproportionate burden
> 
> [List non-accessible section(s)/content/function(s) for which the disproportionate burden exemption, within the meaning of Article 5 of Directive (EU) 2016/2102 is being temporarily invoked]
> 
> (c)
> 
> the content is not within the scope of the applicable legislation
> 
> [List non-accessible section(s)/content/function(s) which is/are out of scope of the applicable legislation].
> 
> [Indicate accessible alternatives, where appropriate].
> 
> Preparation of this accessibility statement
> 
> This statement was prepared on [date xii].
> 
> [Indicate the method used to prepare the statement (see Article 3(1) of Commission Implementing Decision (EU) 2018/1523 (2) )].
> 
> [The statement was last reviewed on [insert date of latest review xiii]].
> 
> Feedback and contact information
> 
> [Provide a description of, and a link to, the feedback mechanism to be used to notify the public sector body of any compliance failures and to request information and content excluded from the scope of the Directive].
> 
> [Provide the contact information of the relevant entity(ies)/unit(s)/person(s) (as appropriate) responsible for accessibility and for processing requests sent through the feedback mechanism].
> 
> Enforcement procedure
> 
> [Provide a description of, and a link to, the enforcement procedure to be used in the case of unsatisfactory responses to any notification or request sent in accordance with Article 7(1)(b) of the Directive].
> 
> [Provide contact information of the relevant enforcement body].

Article 4(1):

> Member States shall ensure that public sector bodies provide in their respective statements at least the mandatory content requirements set out in Section 1 of the Annex.

#### Headings do not match the EU boilerplate

Annex Section 1 specifies these headings for a report:

1. Compliance status
1. Non-accessible content
1. Preparation of this accessibility statement
1. Feedback and contact information
1. Enforcement procedure

However, the report generator inserts these headings in the report: 

1. Conformance status
1. Feedback
1. Limitations and alternatives
1. Assessment approach
1. Formal complaints

#### The introduction does not match the EU boilerplate

Annex Section 1 specifies boilerplate phrases in the introduction.

> [Name of public sector body] is committed to making its [website(s)] [and] [mobile application(s)] accessible, in accordance with [national legislation]
>
> This accessibility statement applies to [insert scope of statement].

However, the report generator only allows the following text in the introduction.

> [Name of public sector body] is committed to ensuring digital accessibility for people with disabilities. We are continually improving the user experience for everyone, and applying the relevant accessibility standards.

#### Text does not match the EU boilerplate in "Compliance status" and "Non-accessible content" sections

Annex Section 1 specifies a sequence of boilerplate phrases in the "Compliance status" and "Non-accessible content" sections. See above in "Expected behavior".

However, the report generator does not allow these boilerplate phrases.

#### Text does not match the EU boilerplate for "prepared on" and "reviewed on" dates

Annex Section 1 specifies two dates.

> This statement was prepared on [date].
> ...
> [The statement was last reviewed on [insert date of latest review]].

However, the report generator only allows insertion of one date.

> This statement was created on [date] using the W3C Accessibility Statement Generator Tool.

#### Links are not allowed for "feedback" and "enforcement"

Annex Section 1 specifies two links.

- A link to the feedback mechanism to be used to notify the public sector body
- A link to the enforcement procedure to be used in the case of unsatisfactory responses

However, the report generator does not allow insertion of these links.

### Note

This issue only addresses English. Note that the EU specifies a model accessibility statement in 23 languages. https://eur-lex.europa.eu/eli/dec_impl/2018/1523/oj

**Comment by nitedog** [comment]
Thank you for your comments. It seems you assume that the model accessibility statement must be used verbatim, which may not be the case. We will look into some aspects more closely.

**Comment by mitchellevan** [comment]
I agree @nitedog, discussion is warranted. Any particular jurisdiction might be fine with the current sequence and wording from the generator.

Data point: the UK Digital Service seems to expect their public sector bodies to include some "legally required" phrases. https://www.gov.uk/government/publications/sample-accessibility-statement/sample-accessibility-statement-for-a-fictional-public-sector-website

**Comment by nitedog** [comment]
Agree. That wasn't the case when we created the tool. I added issues #133, #134, and #135 that could help address most of the issues you raised.

**Comment by nitedog** [comment]
In addition to the changes proposed above, the guidance also states:

> Note that in some situations you may be required to provide particular content in your accessibility statements. For example, there are specific requirements for accessibility statements in relation to the EU Web Accessibility Directive.

This statements generator is not designed exclusively for the EU Directive but also for other uses. Tweaks may be needed but the generated statements should be mostly compatible.
