### ISSUE TITLE
Remove incorrect example "or real-time captioning"

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-statements#144]
### Currently

This text appears in an expandable section.

> Sometimes you may be applying more accessibility requirements than those specified in the accessibility standard stated above. For example, you may be providing sign language videos or real-time captioning for live media. Here you can list these additional accessibility requirements.

### Expected

Remove "or real-time captioning for live media". In context, it implies incorrectly that real-time captioning is not among the requirements listed above, when in fact it is a WCAG level AA success criterion.

If you want to replace it with a different second example, how about "or a plain-language version of web content". (I might be biased, because these both happen to be requirements for public sector website home pages in Germany.)

**Comment by nitedog** [comment]
While the text does not explicitly refer to Level AA, it may indeed be a common assumption.
