### ISSUE TITLE
[comprehensive comment]

### ISSUE THREAD

**Issue by nrhsinclair** [w3c/wai-statements#16]
I think this language should be changed to move the problem away of the individual and more to the site:

I’m experiencing a failure 
We apologize for your inconvenience. Although we strive to have all parts of our website accessible, irregularities can always occur. 

suggest change failure, inconvenience, and irregularities

**Comment by AccessibilityNL** [comment]
The idea was to address the user of the website, people with disabilities as primary audience. They should feel addressed by the text of the statement. This is why we wrote as if the user of the website is reading this and not the organization sending information. Organizations are invited to change the text when they place it on their website.  Does this answer you comment?
