### ISSUE TITLE
[comment] text edit

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-statements#26]
https://w3c.github.io/wai-statements/planning/statements/example-1/
https://w3c.github.io/wai-statements/planning/statements/example-2/
https://w3c.github.io/wai-statements/planning/statements/example-3/

"We will try to answer your feedback within **2 work days office working days**."

should be:

We will try to answer your feedback within **2 office working days**.

Partially conformant means that **Some** parts of the content do not fully conform to the accessibility standard (you can indicate these parts in later sections of this form).

should be: 

"some"

https://w3c.github.io/wai-statements/planning/statements/example-3/
Homepage: Multiple images without a textual alternative **because Editorial mistakes.** Repair in 2 days. Contact us.

should be:

Homepage: Multiple images **exist** without a textual alternative **due to editorial mistakes.** Repair in 2 days. Contact us.

**Comment by AccessibilityNL** [comment]
Thanks for the comments, help and for the proposed solutions. We will start working on the comments Tuesday and will include these. Thanks again! 
Eric and team.

**Comment by nitedog** [comment]
Fixed, many thanks.
