### ISSUE TITLE
Example Accessibility Statement 1

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-statements#28]
Minor editorial suggestions:

Paragraph:  "Conformance status"

- Instead of the having the url in the paragraph, suggest to replace it with wording "The Citylights Inc. website" (with the link on the wording).

- In this paragraph, some caps should be lower case, specifically, "Partially" (straight after the url)

- the "s" in  "that Some parts"

Paragraph "Feedback":

- Instead of "Write us at", would prefer "Write to us at"

Last sentence:
Perhaps simplify: "We will try to answer your feedback within 2 work days office working days."
to "We will try to answer your feedback within 2 working days."

**Comment by nitedog** [comment]
Fixed, many thanks.
