### ISSUE TITLE
[important] pages titles, nav, button

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-statements#29]
Please think about the titles and navigation wording -- from users' perspective. An idea:

title: Developing an Accessibility Statement
nav: Developing an Accessibility Statement

title: Accessibility Statement Generator Tool  (since "tool" is used throughout the text)
nav: Generator Tool

title: Minimal Accessibility Statement Example
nav: Minimal Example

title: Expanded Accessibility Statement Example
nav: Expanded Example

title: Complete Accessibility Statement Example
nav: Complete Example

Related issue: Think about the text on the button on the first page. Maybe want to use "generate" instead of "create" to match other wording? Also, I slightly prefer not "your".

button: Generate accessibility statement
or
button: Generate an accessibility statement

(some more thoughts on title are in [27 Sept minutes](https://www.w3.org/2018/09/27-eo-minutes.html))

**Comment by slhenry** [comment]
see also https://github.com/w3c/wai-statements/issues/30 questioning "Generator"

**Comment by nitedog** [comment]
Done. Please re-open issue if you feel your concern was not sufficiently addressed. More discussion of the term "Generator" is expected under issue #30

**Comment by slhenry** [comment]
looks good!
