### ISSUE TITLE
[comment] simplify language

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-statements#31]
Would be good to have a skilled editor do any edit pass to simplify language, use active voice, etc.

Example of opportunities for improvement :)
> Also linking and naming them consistently across the pages of your website, and across websites and mobile applications that share a common “look and feel”, supports findability.

**Comment by nitedog** [comment]
Yes, it would be good to have. We are doing our best and continually revising the content to improve it. Please let us know of specific suggestions for improvement when you have them. Thanks.
