### ISSUE TITLE
[comment] Simpler language

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-statements#33]
Example 2 Accessibility statement:

- similar comments as made previously for Example 1

- heading "Additions to the requirements" - is the heading necessary?

- in the paragraph under "Additions to the requirements", could the following sentence be simplified  "When an authenticated session expires, the user can continue the activity without loss of data after re-authenticating."

**Comment by nitedog** [comment]
Fixed typos. Opened new issue #46 on "additions to the requirements" heading (now called "additional accessibility").
