### ISSUE TITLE
[comment] Editorial suggestions Example 3

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-statements#34]
I think some editing would be good in the following areas:

- Paragraph "Measures taken".   Maybe the bullet points should be in the past or they could be reworded

- Paragraph "Limitations and alternatives".  Suggested change:  "we are working on solutions for know issues. " to "we are working on solutions for known issues." (add "n" to know")
- The sentences which follow aren't very clear "Please try the solutions provided below or if you experience that this list is not complete, contact us.
Homepage: Multiple images without a textual alternative because Editorial mistakes. Repair in 2 days. Contact us."

**Comment by nitedog** [comment]
Fixed, many thanks,
