### ISSUE TITLE
[comment] Example statements in nav

### ISSUE THREAD

**Issue by iamjolly** [w3c/wai-statements#35]
Instead of...

* Example 1
* Example 2
* Example 3

...in the navigation, I propose we add something that clarifies the examples a bit, such as:

* Minimal Example
* Expanded Example
* Complete Example

or 

* Example 1 (Minimal)
* Example 2 (Expanded)
* Example 3 (Complete)

**Comment by nitedog** [comment]
Done, many thanks.
