### ISSUE TITLE
[comment] strikethroughs in expand/collapse buttons 

### ISSUE THREAD

**Issue by iamjolly** [w3c/wai-statements#36]
I dislike the strikethrough treatment in the disabled button states for the expand all/collapse all buttons. 

Perhaps we can hide the disabled button via `display:none` using a CSS class/rule instead?

**Comment by rvantonisse** [comment]
This is base functionality inherited from the [wai-website-theme](https://github.com/w3c/wai-website-theme). Maybe we can tweak this up inside the generator.html  @yatil ? Or is an edit for the theme script required?

@iamjolly : I think the reason for the expand/collapse-all functionality buttons both are displayed is that not all sections might be expanded / collapsed. This would require a different approach to the technique.

**Comment by yatil** [comment]
This is standard WAI website component. We don't use `display: none` so we don't have to manage focus and shenanigans. Plus, it can be disorienting if there is sometimes one button and sometimes two buttons visible.

I’ll close this as wontfix. :-)
