### ISSUE TITLE
[comment] Generator "Summary"

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-statements#45]
On the "Create an Accessibility Statement" page, I don't feel that the content in the Summary box is an actual summary of the page. I think this is okay though. 

Since this content is very important information, I would like to consider re-titling this box to say "Before You Begin" rather than "Summary." I think it will call more attention to the few sentences, which in my opinion are vitally important to know.

**Comment by nitedog** [comment]
Changed from "Summary" to "About this Generator". Please re-open issue if this does not sufficiently address your concern.
