### ISSUE TITLE
Heading "Audience", second bullet point - attempt to clarify the sentence

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-statements#6]
Current sentence: "The requirement could come from the own organization, an EU Directive etc. They will have a internationally harmonized model and guidance to generate an accessibility statement including an example for the page markup."
Suggested stylistic change:
"The requirement could be from the organization, itself, or from a broader initiative such as the EU Directive etc., which provides an internationally harmonized model and guidance to generate an accessibility statement, including an example for the page markup."

**Comment by nitedog** [comment]
Changed to: "The requirement could be from the organization, itself, or from a broader initiative such as the EU Directive etc. This guidance provides an internationally harmonized model to generate an accessibility statement, including an example for the page markup."
