### ISSUE TITLE
Not displaying info if it is not filled out [ED ]

### ISSUE THREAD

**Issue by Sylvie42** [w3c/wai-statements#70]
Location: generated statement.
Suggestion: if the person filling out the statement does not write anything in one of the fields for feedback in section "Feedback options", do not display it in the generated statement.
I filled out the form with e-mail and phone number, leaving postal address blank. 
When the statement is generated, you can see as third bullet: "Postal address: POSTAL_ADRESS". 
Suggestion: delete the bullet in feedback options if nothing has been typed in one of the fields.
Otherwise, if it is not possible, postal address should be made mandatory.

**Comment by rvantonisse** [comment]
Merged, closing
