### ISSUE TITLE
[ED] Tech Used numbering starts wrong

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-statements#73]
In the "Technologies used" input section of the generator page, when you add another input using the Add another technology button, it adds a new field that is titled "Other 6." I think this should start with the label "Other 1" so that a screen reader user is not wondering what happened to Other 1 through Other 5.

Maybe even have the "Other 1" label and field showing by default so that it matches the other parts of this page and is more consistent.

**Comment by rvantonisse** [comment]
Thanks, fixed! Closing
