### ISSUE TITLE
[ED] add "created by <tool>" link to the generated statements

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-statements#76]
Add something along the lines of "this accessibility statement was created by using <generator tool>" to the end of the generated accessibility statements, to link back to the generator tool (for promotion, branding, acknowledgement, ...).

**Comment by bakkenb** [comment]
+1  Excellent idea

**Comment by rvantonisse** [comment]
Addition sits ready at #94 , feel free to edit contents of reference to generator.

**Comment by nitedog** [comment]
Change made as described above.
