### ISSUE TITLE
[ED] Make field label itself stand out from example included in it

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-statements#80]
> Visitor Address (Example: "Main Street 1, 234 Example Ville")

Make it easier to visually differentiate the actual field label from the Example.

Ideas on how:
* bold labels: **Visitor Address** (Example: "Main Street 1, 234 Example Ville")
* italicize example: Visitor Address _(Example: "Main Street 1, 234 Example Ville")_
* in addition to bold labels or italicized examples, make example gray text (with 7:1 ratio)

I think I'd find it most usable to bold the field labels and make the examples a 7:1 gray.

**Comment by yatil** [comment]
/me thinks bolding the label is enough. FTR the 7:1 gray would be #525252 against the blue-ish background color when the field is focused. I can add classes to our main style sheet for this. (NB: Always good to add yet another gray color to our [myriad of grays](https://w3c.github.io/wai-website-components/components/detail/colors.html) ;-) )

I think we should either change color or italicize, doing both might even more &lt;em>phasize the example.

**Comment by rvantonisse** [comment]
I have split examples with emphasis from labels in #87

**Comment by nitedog** [comment]
Change made as described above.
