### ISSUE TITLE
[later OK] Default intro wording

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-statements#97]
_Sorry I didn't catch this earlier. It is **not** a show stopper for publication of the first version. It can be addressed after publication._

Currently:
> [organization] is committed to ensuring digital accessibility for people with disabilities. We are continually improving the user experience for everyone, and applying the relevant accessibility standards.

I'm not comfortable with the tool adding that info. It may not be correct for many organizations. It promises a lot and if it becomes default wording, it will lose meaning.

(Also, I'm not keen on "relevant accessibility standards" over WCAG 2.1.)

**Comment by nitedog** [comment]
Do you have a proposed wording?

**Comment by rvantonisse** [comment]
> (Also, I'm not keen on "relevant accessibility standards" over WCAG 2.1.)

We could mention the actual selected standard at "Accessibility standards applied" here;

For example:
`...and applying the relevant accessibility standards.` becomes `...and applying the WCAG 2.1 AA standard.`

**Comment by slhenry** [comment]
How about a summary conformance statement from the data provided, e.g.:

> Citylights WebStore is partially conformant with WCAG 2.1 level AA.
